### ISSUE TITLE
suggestion for readme.md

### ISSUE THREAD

**Issue by netalex** [mikejhale/starter-plugin#1]
the repo does'nt have a package.json.
it will be useful for newbies to state in readme to launch something like this before `gulp`:

`npm install --save-dev gulp gulp-sass jshint gulp-jshint gulp-concat gulp-uglify gulp-rename gulp-wp-pot gulp-sort gulp-token-replace`

(JSHINT is needed because of this: https://stackoverflow.com/a/34010722/2079428)
BTW, tanks you a lot for this very usefull streamline and simple boilerplate!

**Comment by netalex** [comment]
correction: the package.json IS prsent, but it is (i think uncorrectly) in `starter-plugin/stylesheets/`

**Comment by mikejhale** [comment]
Changes made to readme and moved package.json to root folder.
